version: "3.7"

services:
    mosquitto:
        image: eclipse-mosquitto
        restart: always
        ports:
        - 1883:1883
        volumes:
        - "mosquitto:/mosquitto/"
    node-red:
        image: nodered/node-red:latest
        restart: always
        ports:
        - 1880:1880
        volumes:
        - "node-red-data:/data"
volumes:
    node-red-data:
    mosquitto: